### ISSUE TITLE
Caused 404 error using with Libresonic v6.2

### ISSUE THREAD

**Issue by slfmoon** [ghenry22/Subsonic_Synology#11]
https://github.com/Libresonic/libresonic/releases/tag/v6.2

I'd like to use this script with Libresonic v6.2 on DS215j / DSM 6.1.1-15101 Update 4
However, I replaced subsonic.war with libresonic-v6.2.war (renamed as subsonic.war) and turn on in control panel, it causes 404 Error.

HTTP ERROR: 404

NOT_FOUND
RequestURI=/index.view

Powered by Jetty://

Use with Libresonic v6.1, I can see index.view properly (but it's too slow...)
Which parameter do I have to change using with Libresonic v6.2?

**Comment by ghenry22** [comment]
Hi, I really don't know anything about libresonic.  This project is for maintaining the subsonic installer for synology.

You're welcome to fork the project and try to make it work as it's publicly available!
