### ISSUE TITLE
new version 6.1.1 ?

### ISSUE THREAD

**Issue by greee-fr** [ghenry22/Subsonic_Synology#12]
A new version is available on subsonic website, can you compile/package it for synology hardwares please ?

**Comment by billraff** [comment]
Dropped by to ask the same. Thanks for your work on this project.

**Comment by ghenry22** [comment]
I will build and release the new version this week

**Comment by HarleyKhr** [comment]
Week has ended, still no new version... sad :(

**Comment by ghenry22** [comment]
Sorry life getting in the way, will have a build done soon

**Comment by billraff** [comment]
No problem, ghenry22. If there is any way I can help let me know. I'm not a developer but can follow instructions and have time to kill.

**Comment by ghenry22** [comment]
built and released as promised.
