### ISSUE TITLE
Subsonic 6.1.2 released

### ISSUE THREAD

**Issue by billraff** [ghenry22/Subsonic_Synology#14]
When possible could you create package for 6.1.2? It has a fix for a Sonos issue. Since I use Subsonic with Sonos would be nice to have the fix.
Thanks

**Comment by ghenry22** [comment]
no problem will release an update in the next few days

**Comment by bareland** [comment]
Would be great to get the 6.1.2 fixed for Sonos.....
Thanks

**Comment by savarick** [comment]
Thank you

**Comment by scottia** [comment]
6.1.3 is now released also

**Comment by AdrianoCGN** [comment]
When will the new version (6.1.3) be released for Synology?

**Comment by ghenry22** [comment]
6.1.2 and 6.1.3 releases published, check the releases page for downloads
