### ISSUE TITLE
synology 6.13 ?

### ISSUE THREAD

**Issue by bigcid10** [ghenry22/Subsonic_Synology#16]
What happened to the update for synology DSM ?
we didn't even get 6.12.

**Comment by AdrianoCGN** [comment]
Any news ?

**Comment by philler3000** [comment]
"we didn't even get" did you pay? no? than pay some respect.

**Comment by ghenry22** [comment]
I will be running builds tomorrow and will make both 6.1.2 and 6.1.3 available on the releases page.

Sorry for the delay publishing them, life got in the way...as it does

**Comment by bigcid10** [comment]
"we didn't even get" did you pay? no? than pay some respect.
Ah... Yea!! 
DID YOU!

**Comment by bigcid10** [comment]
ok,Thank you

**Comment by ghenry22** [comment]
6.1.2 and 6.1.3 releases published, check the releases page for downloads
