### ISSUE TITLE
Use old backup files?

### ISSUE THREAD

**Issue by bennett4senate** [ghenry22/Subsonic_Synology#22]
Hi, I've got everything working and installed, and Subsonic is running off a static IP on the Synology. But I would prefer to use the backup db files from my previous Subsonic installation on my Windows PC so I retain all my existing playlists, starred tracks, etc.
I'm following your instructions from the bottom of the Releases tab to move my Subsonic backup files from my previous installation to Synology:

> copy the folders and files above to the new install location it will be something like `/volume1/@appstore/Subsonic`

> volume will depend on your setup.

I don't know how to navigate to` /volume/@appstore/Subsonic.` Via the file browser in PC? Via the DSM I'm running (DSM 6.1.5-15254 Update 1)? Via command line? I've tried them all and don't see the `/@appstore` folder. How do I get there and put the files in the right place?

> then `sudo chown -R subsonic:users /volume1/@appstore/Subsonic`

I'm assuming this is done through command line on a computer that has the Synology mounted as a share?

I appreciate you building this SPK file and I think this is the last piece to getting it set up exactly how I'd like to run it. Appreciate the help. Thanks.

**Comment by ghenry22** [comment]
You need to connect into your Synology server using SSH, you then use the Linux command line on the Synology box to complete the steps of copying and setting ownership etc.  If not familiar with Linux potentially bug a friend who is to help out.
