### ISSUE TITLE
Time Out accessing the Web App

### ISSUE THREAD

**Issue by jomofcw** [ghenry22/Subsonic_Synology#23]
Hello,

First of all : thanks for your work.
Accessing "http://192.168.0.5:4040/" (from my local network, "192.168.0.5" is my NAS local IP) it results in a timeout... So I can't access anything about Subsonic :'(.
JAVA and Plex well installed (the first one from official Synology package, the other from synocommunity) and running. Subsonic is running too, and I give the subsonic user the RW rights on my "music" folder.

Any idea about what's going wrong there, please ?

Thanks for your help.

**Comment by jomofcw** [comment]
Looking the log from package manager, all seems to be OK.
![synology-subsonic-log](https://user-images.githubusercontent.com/876663/41066773-65bf61e2-69e3-11e8-8779-4f2fe10d939c.jpg)

I've tried with Java8 then with Java7 (reinstalling subsonic after change, and reboot) but same issue.

**Comment by maria95posteonet** [comment]
Try accessing from your mobile phone not using your local wifi network but cellular data it can be an issue with some routers

**Comment by MonsieurPoutounours** [comment]
@jomofcw Is the firewall activated on your Synology device ? If it is, you have to create a rule to allow port 4040.

**Comment by ghenry22** [comment]
I can't recreate this at all so I presume that it is likely to be firewall related as mentioned.  Will close this ticket now, if this issue re-occurs please let me know and I'll take a look again.
