### ISSUE TITLE
DSF files don't appear

### ISSUE THREAD

**Issue by cittaa** [ghenry22/Subsonic_Synology#24]
I have just installed Subsonic Server 6.1.3 in Synology. 
I have added dsf to the list of music files in General Settings. 
After Scan Now Media Folders, only dsf files don't appear in Index. 
Is it nomal?

**Comment by ghenry22** [comment]
Closing at this is more a question for the subsonic forums on how to setup subsonic.  This repo is specifically for issues related to the synology builds.
