### ISSUE TITLE
DSM Update Seems To Have Broken This

### ISSUE THREAD

**Issue by rmcellhiney** [ghenry22/Subsonic_Synology#25]
Applied DSM 6.2.1-23824 today and Subsonic 6.1.3. quit working.  Tried uninstall/reinstall but still fails.  Would love to see this working again.  Thanks!

**Comment by tinnec** [comment]
I have a DS216+II and have upgraded to DSM 6.2.1-23824 too, however my Subsonic 6.1.3 (build e408c9) works well, haven't touched it at all.

**Comment by rmcellhiney** [comment]
It has been running perfectly on my DS1515+ for quite some time.  I use is everyday.  After installing the DSM update yesterday I noticed the Subsonic service had stopped.  Perhaps a coincidence?  When I uninstall and reinstall I am getting a "Failed to install "Subsonic".  Error: Can not start subsonic during install.  And I get this message if I have the "Run after installation" checked or unchecked.

![subsonicerr](https://user-images.githubusercontent.com/16226620/46740251-00fc4d00-cc68-11e8-9d46-f068a867fd4d.JPG)

There does not seem to be any error logs available other than the standard, "Failed to install package [Subsonic]. in the General logs.

Thanks

**Comment by rmcellhiney** [comment]
Follow up for anyone having similar issue.  I purchased and installed 4G RAM for a total of 6G and this addressed my problem.

**Comment by ghenry22** [comment]
It’s a shame about the error, I might have to see about setting a more conservative default memory allocation.

This release definitely works fine on latest DSM, I have tested it personally.

Will close this issue now as there is already another open for adjusting memory.
