### ISSUE TITLE
6.1.4 is out !

### ISSUE THREAD

**Issue by greee-fr** [ghenry22/Subsonic_Synology#27]
Hi, 6.1.4 is out on subsonic website
Will this usefull spk package be update soon ?
Thanks
Greg

**Comment by ghenry22** [comment]
Yes I will build the new version this week, thanks for the heads up.

**Comment by greee-fr** [comment]
soon ?

**Comment by MonsieurPoutounours** [comment]
6.1.5 is out. Maybe some of us can help building packages ?

**Comment by ghenry22** [comment]
6.1.5 is built and available on the releases page, get it while it's hot...
https://github.com/ghenry22/Subsonic_Synology/releases
