### ISSUE TITLE
Refused to connect

### ISSUE THREAD

**Issue by maria95posteonet** [ghenry22/Subsonic_Synology#3]
Thanks a lot for this -

installed it from scratch, Perl and Java had to be installed first 

one minor thing for possible update, I'm not sure if this is because of Synology DSM so you can't do anything about it, but - the message to install prerequisite packages doesn't appear before after the Subsonic .spk has been uploaded, it would be better if this check and message was done first, I had to upload the whole Subsonic .spk twice because I had neither Perl or Java first

**Comment by ghenry22** [comment]
@maria95posteonet  yeah I know what you mean about waiting for it to upload just to find out that you need to install other packages first but there is nothing I can do about it unfortunately.  With SPK packages it needs to get the whole thing and start unpacking it before it can read what other packages are required.

**Comment by maria95posteonet** [comment]
OK makes sense - no biggie at all - thanks again for compiling this we've been waiting years there's nothing comparable
