### ISSUE TITLE
6.16 is out

### ISSUE THREAD

**Issue by mamema** [ghenry22/Subsonic_Synology#33]
!

**Comment by scienex** [comment]
come on, be patient...

**Comment by ghenry22** [comment]
Updated release will be on it's way shortly

**Comment by mamema** [comment]
!
🙂
________________________________

**Comment by jdemattia** [comment]
I added a pull request for this a while back, my fork is updated to 6.1.6.

**Comment by johde** [comment]
I added a pull request for this a while back, my fork is updated to 6.1.6.

**Comment by ghenry22** [comment]
updated release out some time ago so closing this.  Thanks for the PR.
