### ISSUE TITLE
Can I not change port for this ?

### ISSUE THREAD

**Issue by maria95posteonet** [ghenry22/Subsonic_Synology#4]
Hi

You mentioned changing from default 4040 port in your old instructions about how to manually install Subsonic on Synology, but there's no mention of this now you've made this excellent proper package :) Originally that change was made to the subsonic.sh file I think? I stopped the package, edited the file, started the package at new port. 

I just followed your OLD instructions and changed the port number in that file to my preferred one, for this install. This package has worked .... mostly. I guess if it didn't work due to me changing the port, it would not work ever at all, right ? Because it's been working most of the time but occasionally there are server timeout and server not found error messages. 

Reason I ask is I just found another file in /volume1/@appstore/Subsonic called simply "config" where the default 4040 port is specified, rather than the one I changed to in that other file - so could that cause problems because the program will sometimes refer to where it says 4040 port rather than subsonic.sh where it says my custom port ?

The, as specified, automatically generated file "subsonic.properties" has my specified port listed. 

Also, a completely different thing, but - the media library settings "fast access for network drives" checkbox. I've never found any explanation of what that actually does ? But people avoid against it sometimes without explaining why. And now with the actual Subsonic program on the NAS itself, whats correct ? I ticked that box because my NAS is fairly low powered to have to reduce resource use wherever I can. But are there disadvantages ?

**Comment by ghenry22** [comment]
Hi,

There is no user interface for changing the port that this package uses.  You can, of course, manually edit configuration files if you wish but these changes will not necessarily be reflected in the DSM user interface.

I would recommend leaving the port at it's standard value as there isn't really any reason to change it.  If you want it to be accessible on a different port externally then setup a port forwarding rule on your router.

I believe the synology also had some way of adding an proxy that would allow you to do port forwarding on the synology itself as well but I'm not sure.

Unless subsonic has crashed or is not running then server time outs or connection errors are most likely related to something else on the network or in between you and the server.  When it is first indexing files and first starting up it will take a little while to get going but this is just normal startup time for a java app and a IO intensive task like indexing lots of small files.

As for the fast access mode this just means it only scans for new files in your music collection once a day, not sure if it does anything else.  Better to ask on the subsonic forums about that one.
