### ISSUE TITLE
Last update to install.sh did not make it into the package

### ISSUE THREAD

**Issue by genesispc** [ghenry22/Subsonic_Synology#5]
Hey, I just tried installing the spk you created and think it is fantastic. I just wanted to find out if you could regenerate the spk with the updated install.sh file that points to the correct synology ffmpeg location. As a work around I installed serviio, but left it disabled.

Also the icon does not appear in the menu. It turns up as a box, with the name subsonic below it.

**Comment by ghenry22** [comment]
Yes I will be releasing an update to fix the ffmpeg issue.

That's an odd one with the image, I'll look into it, it's working fine on my synology so I'm.not entirely sure why it wouldn't show.

What synology.model and DSM version are you using?

**Comment by genesispc** [comment]
I'm using it in a DS214play with version 6.1 installed.

**Comment by ghenry22** [comment]
thanks for the info I will look into it and see what I can find.  I will put out an update in the next couple of days which adds access to the system transcoder

**Comment by ghenry22** [comment]
This update has been released.  I couldn't find anything specific with the icon, I will have to do a bit of research into whether dsm6.1 or your model want a different size icon.

**Comment by genesispc** [comment]
Cool. I'll have to try it out :-)

**Comment by genesispc** [comment]
Just a quick note to let you know the ffmpeg selection now works :-)

**Comment by maria95posteonet** [comment]
Will try this now - so simply grabbing the .spk file and uploading it will also update other references throughout to transcoder paths etc. ? 

Regarding transcoding, I am not sure how useful / legitimate / legal these links are - I read that apparently Synology themselves are breaking the law with ffmpeg that they use somehow - but that should be no problem if the user sets it up herself - are any of these potentially of use ? 

All that would be required would be a link and perhaps a syntax with those crazy transcoding parameter to paste into Subsonic settings for those of us who have no idea how to write that up :)

Synocommunity Cytec ffmpeg v3.1.2-4
https://synocommunity.com/package/ffmpeg

How to decode DTS on Synology NAS
http://www.letestde.fr/2016/12/16/tuto-comment-decoder-le-dts-sur-un-nas-synology/



FFmpeg with DTS codec for Synology NAS
https://nunobhorta.com/enable-ffmpeg-dts-synology-video-station/

FFMpeg with DTS another link
https://mega.nz/#F!bF4TiIjK!O9AQKJiVoSrXpyBqrKCNRw

AudioTools Simple SPK Server Synorepo.tk (http://synorepo.tk/index.php?fulllist=true)
Audio Tools v1.1-1contains cuetools, shntool with FLAC support, and LAME.
http://synorepo.tk/packages/audio-tools_evansport_1.1-1.spk

SPKItalia FFmpeg with DTS enabled FFmpeg v1.0-0005
http://spk.synologyitalia.com/
http://spk.synologyitalia.com/packages/FFmpegWithDTS-evansport-1.0-0005.spk


Madsonic Transcode Pack Linux x64

Info:
http://beta.madsonic.org/pages/transcoding.jsp
Download:

http://beta.madsonic.org/pages/request.jsp?branch=transcode&target=20161222_madsonic-transcode-linux-x64.zip

(Madsonic has an attempt at a Synology .spk but it does definitely not seem to be a developer priority and it has never worked for me, nor for anyone else is my impression, either way it's only fair to stay loyal the original and best Subsonic)

**Comment by ghenry22** [comment]
this update just uses the version of ffmpeg that comes with your synology.  As synology have multiple different CPU architectures this is the "safe" way for me to make sure that everyone uses one that works for their hardware.  There is no need to installed any other packages to have basic transcoding support.

If you want to try 3rd party packages of ffmpeg or other transcoders you absolutely can, you just need to add a link to their binary files under subsonics transcoders directory.  Unless you're familiar with Linux though I'd probably just go with the defaults.

**Comment by ghenry22** [comment]
going to close this and I'll open a new issue for the icon display
