### ISSUE TITLE
DSM menu icon sometimes does not display

### ISSUE THREAD

**Issue by ghenry22** [ghenry22/Subsonic_Synology#6]
reported case of menu item not displaying on DS214play with DSM 6.1.

Will need to test with DSM 6.1 when I have a test device available.

**Comment by maria95posteonet** [comment]
Had same issue but it disappeared with 6.1-15047 Update 1.

**Comment by ghenry22** [comment]
this seems to be related to a specific version of DSM 6.1.  I cannot reproduce it on my synology.  If you do come across this issue please ensure that your DSM version is up to date, if you still have the same issue please just log a new issue here with your exact DSM version and subsonic synology version and I will check it out again.
