### ISSUE TITLE
beta 2 ?

### ISSUE THREAD

**Issue by greee-fr** [ghenry22/Subsonic_Synology#9]
Hi all, 
// First, thank you. A good package of Subsonic (already exists in past but was abandoned by maintainers) was really needed. So, thanks !
For some days, Subsonic 6.1.beta2 is out.
Will this package reflect changes soon ?

**Comment by ghenry22** [comment]
I will build a test release with subsonic 6.1beta2 this week

**Comment by greee-fr** [comment]
Cool. I look forward for it

**Comment by ghenry22** [comment]
check the releases page, I have built a beta release with subsonic 6.1beta2
